version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: atividade02-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atividade
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/codigo.sql:/docker-entrypoint-initdb.d/codigo.sql  # <-- carrega automaticamente

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.web
    container_name: atividade02-web
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      MYSQL_ADDRESS: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: atividade
      LANG: C.UTF-8
      MYSQL_INITDB_CHARSET: utf8mb4

volumes:
  db_data:
