version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: atividade02-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atividade
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/codigo.sql:/docker-entrypoint-initdb.d/codigo.sql:ro

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.web
    container_name: atividade02-web
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      MYSQL_DATABASE: atividade
      LANG: C.UTF-8
      TZ: America/Sao_Paulo

volumes:
  db_data:
