pipeline {
    agent any

    stages {
        stage('Cleanup') {
            steps {
                bat 'docker compose down -v || exit 0'
            }
        }

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/losleandro/atividade-jenkins-devops.git'
            }
        }

        stage('Construção') {
            steps {
                bat 'docker compose build'
            }
        }

        stage('Entrega') {
            steps {
                bat 'docker compose up -d'
            }
        }
    }
}
