pipeline {
    agent any

    stages {
        stage('Cleanup') {
            steps {
                // Limpa containers anteriores se existirem
                sh 'docker-compose down -v || true'
            }
        }

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/losleandro/atividade-jenkins-devops.git'
            }
        }

        stage('Construção') {
            steps {
                // Constrói a imagem usando Docker do host
                sh 'docker-compose build'
            }
        }

        stage('Entrega') {
            steps {
                // Sobe os containers em background
                sh 'docker-compose up -d'
            }
        }
    }
}

